### ISSUE TITLE
Add course titles to database

### ISSUE THREAD

**Issue by s-langdon** [janecekm/COSC4P02Project2022#24]
The database tables for `Course` and `Offering` do not currently store any information on the name/title for a course (ex. for COSC 1P02 the course title would be "Introduction to Computer Science"). This information would be really helpful for answering questions like "What is COSC 1P02?" etc. The info can be placed in either (or both tables) at your discretion, but I think we need to have it available somewhere.

Not sure if this info is in the web scraping data already or if we need to modify the scraping strategy too. @Ky-Sch @gpog @Joel-Liju

**Comment by Joel-Liju** [comment]
I am currently working on scraping the cross-listing, the course name from the calendar, so It should be available once I run it in the data-cleaning branch
