### ISSUE TITLE
Fix all testing cases

### ISSUE THREAD

**Issue by janecekm** [janecekm/COSC4P02Project2022#41]

**Comment by Joel-Liju** [comment]
- [x] test if rubbish message, gets brock.ca @Ky-Sch 
- [x]  what is prereqs and what are prereqs @Joel-Liju 
- [x] ['message'] for BotNLP.ProcessQ in 3 ( testing_single_hello_processQ()) @Ky-Sch 
- [x] links selectable from front end @Joel-Liju 
- [x] test if we can get the files properly @Ky-Sch 
- [x] test extractKeywords @Ky-Sch 
- [x] test processKeywords @Joel-Liju 
- [x] test doQuery @Ky-Sch 
- [x] test formQuery @Joel-Liju 
- [x] test all get links Information regarding - can be found at: -  @Ky-Sch 
- [x] Coverage testing @Ky-Sch @Joel-Liju 
- [x] test autocorrection
